<a href="https://colab.research.google.com/github/tanvisonawane34/Python-Libraries/blob/main/Special_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [3]:
from google.colab import files
uploaded = files.upload()

Saving hotel_bookings.csv to hotel_bookings.csv

In [4]:
filepath = "/content/hotel_bookings.csv"
df = pd.read_csv(filepath)

In [5]:
df

,Booking_ID,Booking_Date,Customer_ID,Customer_Name,Age,City,Hotel_Name,Room_Type,Nights,Guests,Price_Per_Night,Total_Bill,Payment_Method,Booking_Status,Rating,Breakfast_Included,Coupon_Code,Check_In_Time,Parking_Available,Loyalty_Member
0,10001,2026-01-19,C2000,Alvin Valdez,57,Pune,Sunrise Inn,Suite,5,2,6538,32690,Cash,Confirmed,4.0,No,NEWUSER,10:00,No,Yes
1,10002,2025-09-20,C2001,James May,19,Pune,Blue Orchid,Suite,5,5,5775,28875,Net Banking,Completed,5.0,Yes,NaN,10:00,Yes,No
2,10003,2026-07-02,C2002,Wyatt Riddle,54,Pune,Royal Stay,Suite,7,5,8825,61775,UPI,Cancelled,3.0,Yes,FESTIVE,12:00,No,Yes
3,10004,2025-10-02,C2003,Christopher Wilkinson,62,Goa,Grand Palace,Standard,2,4,5784,11568,Cash,Checked In,5.0,Yes,NaN,12:00,No,No
4,10005,2026-02-10,C2004,Valerie Pena,22,Pune,Grand Palace,Deluxe,5,4,7332,36660,Cash,Cancelled,3.0,No,NEWUSER,11:00,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,10096,2026-06-14,C2095,Alexandra Kim,41,Pune,Blue Orchid,Deluxe,7,2,5444,38108,Card,Checked In,3.0,No,NaN,13:00,Yes,Yes
96,10097,2026-06-06,C2096,Erin Calderon,34,Goa,Grand Palace,Suite,7,2,5195,36365,Net Banking,Confirmed,5.0,No,NEWUSER,11:00,No,Yes
97,10098,2026-03-04,C2097,Samantha Miller,31,Mumbai,Blue Orchid,Standard,1,3,8977,8977,Card,Checked In,NaN,No,FESTIVE,11:00,Yes,No
98,10099,2026-01-06,C2098,Sarah Norman,49,Pune,Blue Orchid,Deluxe,2,5,2934,5868,Cash,Checked In,1.0,No,NaN,10:00,Yes,Yes
99,10100,2026-04-20,C2099,Jeremy Perez,37,Jaipur,Grand Palace,Deluxe,6,3,3057,18342,Net Banking,Checked In,NaN,Yes,NaN,13:00,Yes,Yes

In [7]:
df.head()

,Booking_ID,Booking_Date,Customer_ID,Customer_Name,Age,City,Hotel_Name,Room_Type,Nights,Guests,Price_Per_Night,Total_Bill,Payment_Method,Booking_Status,Rating,Breakfast_Included,Coupon_Code,Check_In_Time,Parking_Available,Loyalty_Member
0,10001,2026-01-19,C2000,Alvin Valdez,57,Pune,Sunrise Inn,Suite,5,2,6538,32690,Cash,Confirmed,4.0,No,NEWUSER,10:00,No,Yes
1,10002,2025-09-20,C2001,James May,19,Pune,Blue Orchid,Suite,5,5,5775,28875,Net Banking,Completed,5.0,Yes,NaN,10:00,Yes,No
2,10003,2026-07-02,C2002,Wyatt Riddle,54,Pune,Royal Stay,Suite,7,5,8825,61775,UPI,Cancelled,3.0,Yes,FESTIVE,12:00,No,Yes
3,10004,2025-10-02,C2003,Christopher Wilkinson,62,Goa,Grand Palace,Standard,2,4,5784,11568,Cash,Checked In,5.0,Yes,NaN,12:00,No,No
4,10005,2026-02-10,C2004,Valerie Pena,22,Pune,Grand Palace,Deluxe,5,4,7332,36660,Cash,Cancelled,3.0,No,NEWUSER,11:00,Yes,No

In [8]:
df.tail()

,Booking_ID,Booking_Date,Customer_ID,Customer_Name,Age,City,Hotel_Name,Room_Type,Nights,Guests,Price_Per_Night,Total_Bill,Payment_Method,Booking_Status,Rating,Breakfast_Included,Coupon_Code,Check_In_Time,Parking_Available,Loyalty_Member
95,10096,2026-06-14,C2095,Alexandra Kim,41,Pune,Blue Orchid,Deluxe,7,2,5444,38108,Card,Checked In,3.0,No,NaN,13:00,Yes,Yes
96,10097,2026-06-06,C2096,Erin Calderon,34,Goa,Grand Palace,Suite,7,2,5195,36365,Net Banking,Confirmed,5.0,No,NEWUSER,11:00,No,Yes
97,10098,2026-03-04,C2097,Samantha Miller,31,Mumbai,Blue Orchid,Standard,1,3,8977,8977,Card,Checked In,NaN,No,FESTIVE,11:00,Yes,No
98,10099,2026-01-06,C2098,Sarah Norman,49,Pune,Blue Orchid,Deluxe,2,5,2934,5868,Cash,Checked In,1.0,No,NaN,10:00,Yes,Yes
99,10100,2026-04-20,C2099,Jeremy Perez,37,Jaipur,Grand Palace,Deluxe,6,3,3057,18342,Net Banking,Checked In,NaN,Yes,NaN,13:00,Yes,Yes

In [9]:
df.shape

(100, 20)

In [10]:
df.columns

Index(['Booking_ID', 'Booking_Date', 'Customer_ID', 'Customer_Name', 'Age',
       'City', 'Hotel_Name', 'Room_Type', 'Nights', 'Guests',
       'Price_Per_Night', 'Total_Bill', 'Payment_Method', 'Booking_Status',
       'Rating', 'Breakfast_Included', 'Coupon_Code', 'Check_In_Time',
       'Parking_Available', 'Loyalty_Member'],
      dtype='object')

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Booking_ID          100 non-null    int64
 1   Booking_Date        100 non-null    object
 2   Customer_ID         100 non-null    object
 3   Customer_Name       100 non-null    object
 4   Age                 100 non-null    int64
 5   City                100 non-null    object
 6   Hotel_Name          100 non-null    object
 7   Room_Type           100 non-null    object
 8   Nights              100 non-null    int64
 9   Guests              100 non-null    int64
 10  Price_Per_Night     100 non-null    int64
 11  Total_Bill          100 non-null    int64
 12  Payment_Method      100 non-null    object
 13  Booking_Status      100 non-null    object
 14  Rating              90 non-null     float64
 15  Breakfast_Included  100 non-null    object
 16  Coupon_Code         67 non-null     object
 17  Check_In_Time       100 non-null    object
 18  Parking_Available   100 non-null    object
 19  Loyalty_Member      100 non-null    object
dtypes: float64(1), int64(6), object(13)
memory usage: 15.8+ KB

In [19]:
df.describe()

,Booking_ID,Age,Nights,Guests,Price_Per_Night,Total_Bill,Rating
count,100.000000,100.000000,100.000000,100.0000,100.00000,100.000000,90.000000
mean,10050.500000,40.480000,3.960000,3.2100,7204.07000,29209.530000,3.033333
std,29.011492,13.526988,1.994538,1.2972,2759.88753,19891.814689,1.464563
min,10001.000000,18.000000,1.000000,1.0000,2018.00000,2493.000000,1.000000
25%,10025.750000,29.000000,2.000000,2.0000,5090.50000,13394.500000,2.000000
50%,10050.500000,39.000000,4.000000,3.0000,7453.00000,25083.000000,3.000000
75%,10075.250000,52.000000,5.250000,4.0000,9231.75000,40862.500000,4.000000
max,10100.000000,65.000000,7.000000,5.0000,11865.00000,82537.000000,5.000000

In [20]:
df.dtypes

Booking_ID              int64
Booking_Date           object
Customer_ID            object
Customer_Name          object
Age                     int64
City                   object
Hotel_Name             object
Room_Type              object
Nights                  int64
Guests                  int64
Price_Per_Night         int64
Total_Bill              int64
Payment_Method         object
Booking_Status         object
Rating                float64
Breakfast_Included     object
Coupon_Code            object
Check_In_Time          object
Parking_Available      object
Loyalty_Member         object
dtype: object

In [21]:
df.isnull().sum()

Booking_ID             0
Booking_Date           0
Customer_ID            0
Customer_Name          0
Age                    0
City                   0
Hotel_Name             0
Room_Type              0
Nights                 0
Guests                 0
Price_Per_Night        0
Total_Bill             0
Payment_Method         0
Booking_Status         0
Rating                10
Breakfast_Included     0
Coupon_Code           33
Check_In_Time          0
Parking_Available      0
Loyalty_Member         0
dtype: int64

In [22]:
df.nunique()

Booking_ID            100
Booking_Date           89
Customer_ID           100
Customer_Name         100
Age                    44
City                    5
Hotel_Name              5
Room_Type               3
Nights                  7
Guests                  5
Price_Per_Night        99
Total_Bill            100
Payment_Method          4
Booking_Status          4
Rating                  5
Breakfast_Included      2
Coupon_Code             3
Check_In_Time           4
Parking_Available       2
Loyalty_Member          2
dtype: int64

In [23]:
df.sample(5)

,Booking_ID,Booking_Date,Customer_ID,Customer_Name,Age,City,Hotel_Name,Room_Type,Nights,Guests,Price_Per_Night,Total_Bill,Payment_Method,Booking_Status,Rating,Breakfast_Included,Coupon_Code,Check_In_Time,Parking_Available,Loyalty_Member
72,10073,2026-03-22,C2072,William Salazar,27,Bengaluru,Sunrise Inn,Suite,4,4,5167,20668,Cash,Confirmed,5.0,No,SAVE10,11:00,Yes,Yes
32,10033,2025-08-13,C2032,Patrick Rodriguez,49,Goa,Sunrise Inn,Suite,7,2,8964,62748,UPI,Completed,5.0,Yes,FESTIVE,13:00,Yes,No
30,10031,2025-12-16,C2030,John Farmer,31,Pune,Grand Palace,Deluxe,6,2,8403,50418,Net Banking,Completed,5.0,No,NaN,10:00,No,No
23,10024,2025-07-19,C2023,Aaron Morrow,36,Jaipur,Sunrise Inn,Deluxe,2,3,11654,23308,UPI,Confirmed,4.0,Yes,NEWUSER,13:00,No,No
9,10010,2025-08-04,C2009,Ernest Hammond,57,Pune,Royal Stay,Deluxe,7,1,6697,46879,Net Banking,Cancelled,NaN,Yes,FESTIVE,13:00,No,Yes

In [24]:
df.value_counts()

Booking_ID  Booking_Date  Customer_ID  Customer_Name           Age  City       Hotel_Name    Room_Type  Nights  Guests  Price_Per_Night  Total_Bill  Payment_Method  Booking_Status  Rating  Breakfast_Included  Coupon_Code  Check_In_Time  Parking_Available  Loyalty_Member
10001       2026-01-19    C2000        Alvin Valdez            57   Pune       Sunrise Inn   Suite      5       2       6538             32690       Cash            Confirmed       4.0     No                  NEWUSER      10:00          No                 Yes               1
10003       2026-07-02    C2002        Wyatt Riddle            54   Pune       Royal Stay    Suite      7       5       8825             61775       UPI             Cancelled       3.0     Yes                 FESTIVE      12:00          No                 Yes               1
10005       2026-02-10    C2004        Valerie Pena            22   Pune       Grand Palace  Deluxe     5       4       7332             36660       Cash            Cancelled       3.0     No                  NEWUSER      11:00          Yes                No                1
10009       2025-10-27    C2008        Sherri King             65   Goa        Grand Palace  Standard   5       4       3000             15000       Net Banking     Confirmed       2.0     No                  SAVE10       13:00          Yes                No                1
10012       2025-09-12    C2011        Kayla Huffman           40   Pune       Sunrise Inn   Standard   2       3       10282            20564       Cash            Checked In      5.0     No                  NEWUSER      11:00          Yes                Yes               1
10016       2026-03-14    C2015        Kayla Fisher            50   Jaipur     Royal Stay    Suite      3       4       4802             14406       Net Banking     Cancelled       1.0     Yes                 SAVE10       11:00          Yes                Yes               1
10019       2026-02-19    C2018        Robert Schneider        20   Bengaluru  Sunrise Inn   Standard   4       4       3076             12304       UPI             Completed       2.0     No                  FESTIVE      13:00          Yes                Yes               1
10021       2026-06-21    C2020        Erica Norris            26   Mumbai     Sunrise Inn   Standard   7       2       11791            82537       UPI             Confirmed       3.0     Yes                 NEWUSER      10:00          Yes                No                1
10022       2025-08-18    C2021        Andrew Tran             24   Bengaluru  Blue Orchid   Deluxe     5       2       8648             43240       Cash            Confirmed       3.0     Yes                 SAVE10       11:00          No                 No                1
10023       2025-10-06    C2022        Richard Reid            21   Mumbai     Blue Orchid   Suite      6       5       4821             28926       Card            Checked In      3.0     Yes                 FESTIVE      10:00          Yes                No                1
10024       2025-07-19    C2023        Aaron Morrow            36   Jaipur     Sunrise Inn   Deluxe     2       3       11654            23308       UPI             Confirmed       4.0     Yes                 NEWUSER      13:00          No                 No                1
10025       2026-01-03    C2024        Deborah Morrow          54   Bengaluru  Royal Stay    Standard   5       4       4451             22255       Net Banking     Checked In      2.0     Yes                 SAVE10       10:00          No                 No                1
10027       2026-06-05    C2026        Cheryl Ray              41   Mumbai     Lake View     Standard   5       2       5980             29900       Net Banking     Completed       4.0     No                  FESTIVE      13:00          No                 No                1
10028       2025-12-27    C2027        Jeffery Kaufman         37   Jaipur     Blue Orchid   Standard   2       1       3101             6202        UPI             Cancelled       3.0     No                  FESTIVE      11:00          No                 No                1
10029       2025-11-22    C2028        Paige Hammond           58   Pune       Lake View     Deluxe     7       4       11008            77056       UPI             Cancelled       4.0     No                  FESTIVE      13:00          No                 No                1
10030       2026-02-15    C2029        Gloria Mendoza          38   Pune       Grand Palace  Suite      2       4       6913             13826       Net Banking     Confirmed       1.0     No                  SAVE10       13:00          Yes                Yes               1
10033       2025-08-13    C2032        Patrick Rodriguez       49   Goa        Sunrise Inn   Suite      7       2       8964             62748       UPI             Completed       5.0     Yes                 FESTIVE      13:00          Yes                No                1
10034       2025-08-16    C2033        Joseph Smith            32   Jaipur     Royal Stay    Deluxe     2       3       5502             11004       UPI             Confirmed       1.0     No                  SAVE10       10:00          No                 No                1
10035       2026-03-14    C2034        Olivia Rowe             22   Goa        Grand Palace  Standard   1       4       8630             8630        Net Banking     Completed       1.0     No                  SAVE10       11:00          No                 Yes               1
10036       2026-03-27    C2035        Elizabeth Harper        46   Pune       Grand Palace  Standard   1       2       6507             6507        UPI             Cancelled       3.0     No                  FESTIVE      13:00          Yes                No                1
10037       2025-08-29    C2036        Michael Harper          49   Mumbai     Lake View     Deluxe     5       3       9226             46130       UPI             Checked In      5.0     No                  FESTIVE      12:00          No                 Yes               1
10038       2025-08-25    C2037        Kyle Walker             39   Pune       Blue Orchid   Suite      3       3       11688            35064       UPI             Confirmed       4.0     No                  NEWUSER      12:00          No                 Yes               1
10040       2025-10-19    C2039        Jennifer Roberts        23   Bengaluru  Grand Palace  Standard   3       4       6138             18414       Card            Completed       1.0     No                  FESTIVE      13:00          No                 Yes               1
10041       2026-05-01    C2040        Patricia Martinez       49   Jaipur     Sunrise Inn   Standard   1       5       3708             3708        Card            Checked In      5.0     Yes                 FESTIVE      11:00          No                 No                1
10043       2025-08-09    C2042        Angela Williams         39   Jaipur     Grand Palace  Deluxe     7       5       2018             14126       Card            Checked In      1.0     Yes                 NEWUSER      10:00          Yes                Yes               1
10045       2025-08-24    C2044        Dr. Alan Waters         48   Pune       Lake View     Standard   5       3       5652             28260       Cash            Cancelled       1.0     Yes                 FESTIVE      11:00          Yes                Yes               1
10048       2025-09-07    C2047        Abigail Rodriguez       29   Bengaluru  Blue Orchid   Suite      5       2       11008            55040       Cash            Completed       2.0     Yes                 FESTIVE      10:00          Yes                No                1
10049       2026-02-20    C2048        Kyle Holt               55   Goa        Blue Orchid   Deluxe     2       5       2886             5772        Card            Cancelled       2.0     No                  FESTIVE      12:00          No                 Yes               1
10050       2025-11-12    C2049        Jean Williams           61   Jaipur     Grand Palace  Deluxe     1       3       7342             7342        UPI             Checked In      2.0     No                  SAVE10       12:00          No                 No                1
10051       2026-05-11    C2050        Shawna Bowman           60   Jaipur     Sunrise Inn   Deluxe     4       3       8170             32680       Net Banking     Confirmed       5.0     Yes                 SAVE10       10:00          No                 Yes               1
10052       2026-02-21    C2051        Marc Reynolds           51   Jaipur     Lake View     Standard   2       3       2044             4088        Net Banking     Confirmed       4.0     Yes                 FESTIVE      11:00          No                 No                1
10054       2026-03-04    C2053        Carl Knight             37   Pune       Grand Palace  Deluxe     2       1       7914             15828       UPI             Completed       5.0     No                  FESTIVE      13:00          Yes                No                1
10055       2026-05-22    C2054        Angela Oliver           29   Goa        Grand Palace  Suite      6       2       10703            64218       UPI             Completed       2.0     Yes                 SAVE10       13:00          Yes                No                1
10056       2026-02-15    C2055        Jake Mcdonald           25   Pune       Lake View     Deluxe     3       3       2591             7773        UPI             Completed       2.0     Yes                 NEWUSER      10:00          No                 No                1
10058       2026-05-14    C2057        Jacqueline Hall         35   Mumbai     Grand Palace  Suite      1       5       11834            11834       Card            Confirmed       5.0     Yes                 NEWUSER      11:00          No                 No                1
10063       2026-01-16    C2062        Sara Avila              59   Mumbai     Lake View     Standard   3       3       7124             21372       Net Banking     Completed       2.0     Yes                 FESTIVE      10:00          No                 No                1
10064       2025-07-23    C2063        Joseph Garcia           49   Mumbai     Lake View     Deluxe     5       4       10269            51345       Cash            Confirmed       5.0     Yes                 FESTIVE      13:00          No                 Yes               1
10065       2025-09-25    C2064        Robert Cervantes        38   Jaipur     Lake View     Deluxe     2       2       3512             7024        UPI             Cancelled       3.0     Yes                 SAVE10       11:00          Yes                No                1
10069       2025-11-18    C2068        Christina Cook          45   Mumbai     Royal Stay    Suite      5       4       9703             48515       UPI             Completed       5.0     No                  NEWUSER      10:00          Yes                Yes               1
10071       2025-07-31    C2070        Daniel Phillips         25   Jaipur     Lake View     Deluxe     3       5       5736             17208       UPI             Completed       5.0     No                  NEWUSER      11:00          Yes                Yes               1
10072       2025-11-28    C2071        Mr. Micheal Wilson Jr.  58   Pune       Royal Stay    Deluxe     6       4       4453             26718       UPI             Checked In      3.0     No                  FESTIVE      13:00          Yes                Yes               1
10073       2026-03-22    C2072        William Salazar         27   Bengaluru  Sunrise Inn   Suite      4       4       5167             20668       Cash            Confirmed       5.0     No                  SAVE10       11:00          Yes                Yes               1
10076       2025-10-22    C2075        Joseph Chase            53   Bengaluru  Grand Palace  Standard   5       5       7385             36925       Card            Checked In      3.0     Yes                 FESTIVE      10:00          Yes                Yes               1
10077       2025-07-28    C2076        Andrew Alvarez          26   Pune       Blue Orchid   Standard   7       3       11084            77588       UPI             Checked In      1.0     No                  SAVE10       12:00          No                 No                1
10078       2025-12-18    C2077        Fernando Scott          22   Pune       Sunrise Inn   Deluxe     3       3       11297            33891       Cash            Cancelled       5.0     No                  NEWUSER      10:00          Yes                No                1
10079       2025-09-04    C2078        Bobby Moore             37   Bengaluru  Lake View     Standard   1       3       7616             7616        Card            Confirmed       4.0     No                  SAVE10       10:00          Yes                No                1
10080       2025-10-11    C2079        Jerry Cox               42   Pune       Sunrise Inn   Suite      3       5       4586             13758       UPI             Confirmed       5.0     No                  NEWUSER      13:00          Yes                No                1
10081       2026-03-06    C2080        Jason Martinez          47   Jaipur     Blue Orchid   Deluxe     4       1       4604             18416       Cash            Completed       4.0     Yes                 SAVE10       10:00          No                 No                1
10082       2026-06-23    C2081        Ashley Clarke           44   Bengaluru  Blue Orchid   Standard   7       2       11329            79303       UPI             Checked In      2.0     No                  FESTIVE      10:00          No                 Yes               1
10083       2026-02-26    C2082        Sydney Marsh            59   Bengaluru  Royal Stay    Suite      6       5       7729             46374       UPI             Cancelled       3.0     No                  NEWUSER      10:00          No                 No                1
10084       2026-04-18    C2083        James Hart              47   Pune       Lake View     Deluxe     6       5       9786             58716       Net Banking     Cancelled       1.0     Yes                 FESTIVE      12:00          No                 Yes               1
10085       2026-02-27    C2084        Wesley Freeman          35   Goa        Sunrise Inn   Suite      5       2       11865            59325       Card            Checked In      3.0     Yes                 SAVE10       12:00          Yes                Yes               1
10086       2025-11-27    C2085        Kathryn Perry           52   Bengaluru  Lake View     Standard   6       4       3848             23088       Net Banking     Checked In      5.0     No                  FESTIVE      12:00          No                 Yes               1
10087       2025-11-12    C2086        Courtney Farmer         37   Goa        Royal Stay    Deluxe     7       2       9582             67074       Card            Confirmed       1.0     Yes                 FESTIVE      11:00          Yes                No                1
10089       2026-03-10    C2088        Alexis Mckee            18   Goa        Grand Palace  Suite      5       3       8014             40070       Cash            Cancelled       3.0     No                  FESTIVE      12:00          Yes                No                1
10094       2025-12-26    C2093        Charles Miller          19   Mumbai     Sunrise Inn   Deluxe     5       2       7710             38550       Card            Completed       4.0     No                  NEWUSER      11:00          No                 No                1
10095       2026-04-01    C2094        Angela Lewis            44   Jaipur     Royal Stay    Suite      2       1       8411             16822       Card            Cancelled       2.0     No                  SAVE10       13:00          No                 No                1
10097       2026-06-06    C2096        Erin Calderon           34   Goa        Grand Palace  Suite      7       2       5195             36365       Net Banking     Confirmed       5.0     No                  NEWUSER      11:00          No                 Yes               1
Name: count, dtype: int64